version: '3.9'
services:
  app:
    build:
      context: .
    command: ["/wait-for-it.sh", "db", "/entrypoint.sh"]
    ports:
      - '8080:8000'
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    depends_on:
      - db
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=123@456
  db:
    image: postgres:16-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5433:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=123@456
volumes:
  static_volume:
  postgres-data: