services:
  app:
    build:
      context: .
    command: ["/app/wait-for-it.sh", "db", "--", "/app/entrypoint.sh"]
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    depends_on:
      - db
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=123@456
  db:
    image: postgres:16-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=123@456
volumes:
  static_volume:
  postgres-data:
